DROP TABLE assignment CASCADE CONSTRAINTS;
DROP TABLE statistic CASCADE CONSTRAINTS;
DROP TABLE repair CASCADE CONSTRAINTS;
DROP TABLE route CASCADE CONSTRAINTS;
DROP TABLE vehicle CASCADE CONSTRAINTS;
DROP TABLE employee CASCADE CONSTRAINTS;
DROP TABLE division CASCADE CONSTRAINTS;